services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - proxy
    network_mode: "host"

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    restart: always
    network_mode: "host"
