# Use official Python image
FROM python:3.12.3

WORKDIR /app

COPY requirements.txt .

RUN python -m venv /venv
RUN /venv/bin/pip install --no-cache-dir -r requirements.txt

COPY app/Main.py .

EXPOSE 8080 5000

ENV PORXY_IP="0.0.0.0"
ENV SITE_IP="10.0.0.31"

ENV PROXY_PORT=8080
ENV SITE_PORT=5000

CMD ["/venv/bin/python", "Proxy.py"]
